# Generated by Django 4.1.4 on 2024-02-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
